extra["groupName"] = "net.toliner.korgelin"
extra["modVersion"] = "1.1.0"
extra["modName"] = "Korgelin"
extra["kotlinVersion"] = "1.3.70"
extra["annotationsVersion"] = "17.0.0"
extra["coroutineVersion"] = "1.3.8"
extra["serializationVersion"] = "0.20.0"
