extra["groupName"] = "net.toliner.korgelin"
extra["modVersion"] = "1.1.1"
extra["modName"] = "Korgelin"
extra["kotlinVersion"] = "1.4.32"
extra["annotationsVersion"] = "17.0.0"
extra["coroutineVersion"] = "1.4.3"
extra["serializationVersion"] = "1.1.0"
